### PR TITLE
publish: Add initial version of publish command

### PR DESCRIPTION
**Pull request by mike-sul**
This is the publish command code movement from the `compose-publish` project to the `composeapp` one.

The minimum changes have been done to the original version to avoid any regression:
1. Adjust code to the newer docker/moby version usage.
2. Adjust code to the newer version of some system level functionality (e.g. ioutil -> os).
3. Enforce usage of the distribution/registry 2.7.1 to let creation and publishing of an OCI incompatible manifests as it's been working in the `compose-publish` utility. The goal is to avoid any regression.

### CODE REVIEW

**Review by doanac — COMMENTED** [review]
lgtm - The compiler won't include any of this in the compose-app binary that runs on devices, right? i.e. The size of the tool isn't going to grow there because of this.

**Comment by mike-sul** [comment]
> lgtm - The compiler won't include any of this in the compose-app binary that runs on devices, right? i.e. The size of the tool isn't going to grow there because of this.

It will as it is implemented now. The diff is around 2MB. I can tweak the change and enable conditional compilation so the "publish" related won't be included into the binary built for devices. Not sure that 2MB worth code complication though.

**Comment by doanac** [comment]
> Not sure that 2MB worth code complication though.

It's very much worth it. It's a feature you don't want/need on a device and saves 2Mb per device per LmP version.

**Comment by mike-sul** [comment]
> > Not sure that 2MB worth code complication though.
> 
> It's very much worth it. It's a feature you don't want/need on a device and saves 2Mb per device per LmP version.

Let's do the same for `docker build` and `docker push` commands :).

I have different opinion about it, but it is not a big deal, so let's do it.

**Comment by doanac** [comment]
> Let's do the same for docker build and docker push commands :).

You half joke, but the thought crossed my mind while I was typing that response. That could potentially be a huge size reduction in the future ... but not using Docker at all would be an even bigger one.

**Comment by mike-sul** [comment]
> but not using Docker at all would be an even bigger one.

I am up to it :).

**Comment by mike-sul** [comment]
> > Not sure that 2MB worth code complication though.
> 
> It's very much worth it. It's a feature you don't want/need on a device and saves 2Mb per device per LmP version.

Done https://github.com/foundriesio/composeapp/pull/27/commits/7d856fb53f4ecdbc220fb88908b80c9f17a16d3b. The composeapp recipe in LmP doesn't use this repo Makefile so the `publish` command won't be included into the device binary.

**Review by doanac — APPROVED** [review]
thanks!

**Pull request merged**
