### PR TITLE
Add lightway app fetch check

### PR DESCRIPTION
**Pull request by mike-sul**

### CODE REVIEW

**Comment by doanac** [comment]
We'll we be able to quantify how "light" this is once done?

**Comment by mike-sul** [comment]
> We'll we be able to quantify how "light" this is once done?

In which units? :). It is easy to compare two ways of checking if an app is fetched, however those numbers are not quite useful IMO. The diff depends a lot on environment, e.g. storage IO speed, CPU, a number of blobs an app is consists of and their size, etc.

The following is the diff for `home-assistance` app in my env.

`
real	0m0.067s
user	0m0.010s
sys	0m0.023s
`

`
real	0m3.824s
user	0m3.395s
sys	0m0.221s
`

**Comment by mike-sul** [comment]
@detsch Changes to aklite that makes use of the "quick" check as well as result of the app bundle integrity check will be in the next PR to aklite.

**Comment by doanac** [comment]
i was thinking "time" would be a decent way to understand the difference

**Review by detsch — APPROVED** [review]

**Comment by mike-sul** [comment]
> @detsch Changes to aklite that makes use of the "quick" check as well as result of the app bundle integrity check will be in the next PR to aklite.

In my env for app with over 20 blobs the diff in timing is significant, around x50 times.

**Pull request merged**
