### PR TITLE
Make layers manifest optional

### PR DESCRIPTION
**Pull request by mike-sul**
- Extend the test environment with the vanilla registry and tweak test fixtures so test can be run against different types of registry.
- Make the app layers manifest creation and addition to an compose app manifest optional. It allows us creating an OCI-compliant app manifest that the vanilla registry can digest.

### CODE REVIEW

**Comment by mike-sul** [comment]
@doanac This change allows us not adding the "manifests" field into an app manifest which is against the OCI specification and makes us patch the registry. 
Turning off of the "layers manifest" is optional and requires explicit parameter setting,so it is ON as it is now to avoid any regression.
The newer LmP/aklite versions (>= v93) does not need/use this field at all. The field/data are used by the older aklite versions, < v93, however its absence does not break aklite, just no app update size check.
My plan is to enable the "layers manifest" turning off for the dev and new factories, and optionally it can be done to existing production factories on request.

**Comment by doanac** [comment]
> The field/data are used by the older aklite versions, < v93, however its absence does not break aklite, just no app update size check.

People do rely on that check, so we should assume nobody is going to want to use this <v93.

I wonder if there's something we need to document or convey to customer-success with regards to this?

**Comment by mike-sul** [comment]
> People do rely on that check, so we should assume nobody is going to want to use this <v93.
> 
Yes, that's why we are not going to disable "layers manifest" for existing factories unless explicitly requested.

**Comment by mike-sul** [comment]
>>I wonder if there's something we need to document or convey to customer-success with regards to this?

I don't see much reason. I don't see a good way to change it for existing factories because we are never know what LmP version their devices are on. So, we just keep doing the same hack for existing factories.
As for the new factory we just simply disable hacking app manifest, not sure there is any reason to inform customers about this low level detail.

**Comment by doanac** [comment]
> I don't see a good way to change it for existing factories because we are never know what LmP version their devices are on

excellent point. it's about the version you are updating from.

**Comment by mike-sul** [comment]
> > I don't see a good way to change it for existing factories because we are never know what LmP version their devices are on
> 
> excellent point. it's about the version you are updating from.

That's why this PR does not change the default behavior of `compose publish` - the "layers manifest" is added to an app manifest.

This PR adds a new parameter to the `composectl publish` command so we can turn off adding the "layers manifest" if explicitly specified in factory config or if the condition we'll add to source.f.io is met.

**Review by doanac — APPROVED** [review]

**Pull request merged**
